# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b927e3e05825c378db5420c22c66af80195306ccb64be0c5c3a434b3d97338662cfa11da50bfd13984c898b92647c3a52f274e57699d77b4d07d6e7d76daeaca

test:
  secret_key_base: 341a99b1ee85cccccd05823011b1123828f06b590fe106fae84321fdd572f7881379d23da07b19e0070149ea4746854f455dcc8fdc0f8d47b2060a633a7cdf75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
